import { Module } from '@nestjs/common';
import { InventoryAuditService } from './inventory-audit.service';
import { InventoryAuditController } from './inventory-audit.controller';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  CpsTemporales,
  DetDevolucionInventario,
  DetEntradaDesmonte,
  DetEntradaInventario,
  DetInventarios,
  DetRboGarantiaRecogidos,
  DetSalidaMatConsumo,
  DetSalidaPro,
  DetSolicitudMat,
  DetTrasladoReservas,
  DetalleOrdenCompra,
  EncConsumosDelete,
  EncDevolucionInventario,
  EncEntradaDesmonte,
  EncEntradaInventario,
  EncOrdenCompra,
  EncRboGarantiaRecogidos,
  EncSalidaMatConsumo,
  EncSalidaProveedor,
  EncSolicitudMat,
  EncTrasladoReservas,
  InventarioDesmonte,
  InventarioInstalar,
  QrySicteRyg,
  RolloDevInventario,
  RolloEntradaInv,
  RolloInstalar,
  RolloInventarios,
  RolloSalidaMatConsumo,
  RolloSalidaPro,
  RolloTrasladoReservas,
  SerialDevInventario,
  SerialEntradaDesmonte,
  SerialEntradaGarantia,
  SerialEntradaInventario,
  SerialEntregadoRecGar,
  SerialInstalar,
  SerialInventarioDesmonte,
  SerialSalidaMatConsumo,
  SerialSalidaPro,
  SerialTrasladoReservas,
  VisitasRazon,
} from 'src/inventory/entities';

@Module({
  controllers: [InventoryAuditController],
  providers: [InventoryAuditService],
  imports: [
    TypeOrmModule.forFeature([
      CpsTemporales,
      DetDevolucionInventario,
      DetEntradaDesmonte,
      DetEntradaInventario,
      DetInventarios,
      DetRboGarantiaRecogidos,
      DetSalidaMatConsumo,
      DetSalidaPro,
      DetSolicitudMat,
      DetTrasladoReservas,
      DetalleOrdenCompra,
      EncConsumosDelete,
      EncDevolucionInventario,
      EncEntradaDesmonte,
      EncEntradaInventario,
      EncOrdenCompra,
      EncRboGarantiaRecogidos,
      EncSalidaMatConsumo,
      EncSalidaProveedor,
      EncSolicitudMat,
      EncTrasladoReservas,
      InventarioDesmonte,
      InventarioInstalar,
      QrySicteRyg,
      RolloDevInventario,
      RolloEntradaInv,
      RolloInstalar,
      RolloInventarios,
      RolloSalidaMatConsumo,
      RolloSalidaPro,
      RolloTrasladoReservas,
      SerialDevInventario,
      SerialEntradaDesmonte,
      SerialEntradaGarantia,
      SerialEntradaInventario,
      SerialEntregadoRecGar,
      SerialInstalar,
      SerialInventarioDesmonte,
      SerialSalidaMatConsumo,
      SerialSalidaPro,
      SerialTrasladoReservas,
      VisitasRazon,
    ]),
  ],
})
export class InventoryAuditModule {}
